service: second-test

frameworkVersion: '2'

provider:
  name: aws
  runtime: python3.8
  lambdaHashingVersion: 20201221
  iam:
    role: arn:aws:iam::624733648801:role/Role-serverless-function
  deploymentBucket:
    name: codebuildjuver
    serverSideEncryption: AES256
  #deploymentPrefix: serverless/example
  
plugins:
  - serverless-deployment-bucket

package:
  individually: true
  exclude:
    - "**"
ecr:
   # In this section you can define images that will be built locally and uploaded to ECR
   scanOnPush: true
   images:
     test-image:
       path: ./lambdas/
       file: Dockerfile
functions:
  lambda-01:
     image:
        name: test-image
        command:
          - lambda_function.lambda_handler
    
  
