service: second-test

frameworkVersion: "2"
custom:
  AWS_ACCESS_KEY_ID: "Hola1" #${env:AWS_ACCESS_KEY_ID}
  AWS_SECRET_ACCESS_KEY: "Hola2" #${env:AWS_SECRET_ACCESS_KEY}
  AWS_SESSION_TOKEN: "Hola3" #${env:AWS_SESSION_TOKEN}
provider:
  name: aws
  runtime: python3.6
  lambdaHashingVersion: 20201221
  iam:
    role: arn:aws:iam::624733648801:role/Role-serverless-function
  deploymentBucket:
    name: codebuildjuver
    serverSideEncryption: AES256
  #deploymentPrefix: serverless/example
  ecr:
    # In this section you can define images that will be built locally and uploaded to ECR
    scanOnPush: true
    images:
      lambda-01-image:
        path: ./lambda/
        file: Dockerfile  
        buildArgs:
          AWS_ACCESS_KEY_ID: ${self:custom.AWS_ACCESS_KEY_ID}
          AWS_SECRET_ACCESS_KEY: ${self:custom.AWS_SECRET_ACCESS_KEY}
          AWS_SESSION_TOKEN: ${self:custom.AWS_SESSION_TOKEN}

plugins:
  - serverless-deployment-bucket


functions:
  lambda-01:
    image:
      name: lambda-01-image
      command:
        - lambda_function.lambda_handler
