service: serverless

frameworkVersion: "2"


plugins:
  - serverless-deployment-bucket
  - serverless-plugin-split-stacks

custom:
  splitStacks:
    nestedStackCount: 2
    perFunction: false
    perType: false
    perGroupFunction: true
  aws_account: '624733648801'
provider:
  name: aws
  runtime: python3.6
  eventBridge.useCloudFormation: true
  variablesResolutionMode: 20210326
  lambdaHashingVersion: 20201221
  iam:
    role: arn:aws:iam::624733648801:role/Role-serverless-function
  deploymentBucket:
    name: codebuildjuver
    serverSideEncryption: AES256
  stage: dev
 

functions:
  lambda03:
    handler: lambdas/lambda03/lambda_function.lambda_handler
    memorySize: 1024
    timeout: 1
    package:
      patterns:
        - "!**"
        - lambdas/lambda03/*
      individually: true
    events:
      - schedule:
          rate: cron(*/1 8-23 * * ? *)
  
  lambda01:
    handler: lambdas/lambda01/lambda_function.lambda_handler
    memorySize: 1024
    timeout: 1
    package:
      patterns:
        - "!**"
        - lambdas/lambda01/*
      individually: true
    events:
      - schedule:
          rate: cron(*/1 8-23 * * ? *)

  lambda02:
    handler: lambdas/lambda02/lambda_function.lambda_handler
    memorySize: 1024
    timeout: 1
    package:
      patterns:
        - "!**"
        - lambdas/lambda02/*
      individually: true
    events:
      - schedule:
          rate: cron(*/1 8-23 * * ? *)
resources:
  Resources:
    Lambda01LambdaPermission:
      Type: "AWS::Lambda::Permission"
      DependsOn: Lambda01LambdaFunction
      Properties:
        FunctionName: "arn:aws:lambda:${self:provider.region}:${self:custom.aws_account}:function:${self:service}-${self:provider.stage}-lambda01"
        Action: lambda:InvokeFunction
        Principal: 438272768936
    Lambda02LambdaPermission:
      Type: "AWS::Lambda::Permission"
      DependsOn: Lambda02LambdaFunction
      Properties:
        FunctionName: "arn:aws:lambda:${self:provider.region}:${self:custom.aws_account}:function:${self:service}-${self:provider.stage}-lambda02"
        Action: lambda:InvokeFunction
        Principal: 438272768936
